### ISSUE TITLE
Milestone 2

### ISSUE THREAD

**Issue by Kevt-t** [Kevt-t/Milestone#6]
**Problem Statement**
The previous YouTube Video project scope created several limitations based on user feedback. The layout does not provide a great user experience and should be improved to increase traffic to the site. 

**Project Scope**
Create a page layout using a CSS grid that uses a main section that shows the main video that we want to play. There must be a placeholder section below the main video that shows a list of 4 or 5 videos that can be selected to watch next.  

**Deliverables**

- [x] I have reviewed the concept rubric
- [x] I have create stories in GitHub Projects and related stories, issues & task
- [x] I have commented my code for readability and logical flow of information 
- [x] I have added the latest code to GitHub
- [x] I have hosted my project on GitHub pages 
- [x] I have submitted my GitHub Link to Beacon
- [x] I have updated my readme.md to reflect the most updated version of my application
- [x] I use HTML5 elements in my index.html 
- [x] I have embedded a YouTube Video in my index.html
- [x] I have styled my CSS page and displayed my Video on my page that allows users to view and navigate the site easily
- [x] I have properly displayed the video attributes (title, description, watch time etc.) 
- [x] I have documented my code
- [x] HTML files have been documented 
- [x] CSS files have been documented 
- [x] JavaScript files have been documented
