### ISSUE TITLE
Milestone 3

### ISSUE THREAD

**Issue by Kevt-t** [Kevt-t/Milestone#7]
**Problem Statement** 
We’ve received several requests for adding themes to our app. Many users like the theme feature offered by other applications they love using. 

**Project Scope**
Dark and Light themes are popular in demand for our website. Create a default theme that is Light and a Dark theme that can be turned on by clicking a button on the page. Style the button with icons and imagery that speaks to what the button will do if/when it is clicked.

Deliverable

- [x] I have reviewed the concept rubric
- [x] I have create stories in GitHub Projects and related stories, issues & task
- [x] I have commented my code for readability and logical flow of information 
- [x] I have added the latest code to GitHub
- [x] I have hosted my project on GitHub pages 
- [x] I have submitted my GitHub Link to Beacon
- [x] I created implemented a dark and light theme on my website 
- [x] I have added toggle switch & button that interacts with my colored themes
- [x] I have linked my JavaScript file to my application in my index.html 
- [x] Use naming conventions that will be helpful to peers and colleagues reviewing your project 
- [x] I have documented my code
- [x]  Html files have been documented 
- [x]  CSS files have been documented 
- [x]  JavaScript files have been documented
