### ISSUE TITLE
Milestone 4

### ISSUE THREAD

**Issue by Kevt-t** [Kevt-t/Milestone#8]
**Problem Statement**
We don’t know how many users will use the theme button or if it is worth the time to build it. We should track how many requests we get for the button. 

**Project Scope**
Update the application to implement a theme. Create a form using JavaScript, when clicked, a form should popup and collect user data (email,  name, theme) and save it locally. Store the users preferences in Local Storage. Restore the selected theme when the application is loaded. Update the application logic to handle the click event for the theme.

**Deliverables** 

- [x] I have reviewed the concept rubric
- [x] I have create stories in GitHub Projects and related stories, issues & task
- [x] I have commented my code for readability and logical flow of information 
- [x] I have added the latest code to GitHub
- [x] I have hosted my project on GitHub pages 
- [x] I have submitted my GitHub Link to Beacon
- [x] I have added an event handler for the theme change to my application 
- [x] I have implemented the Local Storage API to save & restore user data
- [x] I have documented my code
- [x] Html files have been documented 
- [x] CSS files have been documented 
- [x] JavaScript files have been documented 
- [x] I used document.createElement() to create a form with the following properties 
- [x] Name
- [x] Email 
- [x] Theme
- [x] Submit
